bagpath: "./datasets/example_sequence.bag"
outputpath: "./output/example_sequence"

imudatalen: 7
imudatarate: 200

starttime: 0.0
endtime: 60.0
initAlignmentTime: 10

initposstd: [0.05, 0.05, 0.05]
initvelstd: [0.05, 0.05, 0.05]
initattstd: [1.0, 1.0, 0.5]

imunoise:
  arw: 1.2
  vrw: 6.0
  gbstd: 20.0
  abstd: 2000.0
  gsstd: 500.0
  asstd: 500.0
  corrtime: 0.5

fl_imu_leverarm: [0.0, 0.03, 0.048]
fr_imu_leverarm: [0.0, -0.03, 0.048]
rl_imu_leverarm: [0.0, 0.03, 0.048]
rr_imu_leverarm: [0.0, -0.03, 0.048]

if_estimate_leverarm: false
LegIMU_Leverarm_STD: 0.005
LegIMU_Leverarm_Noise: 0.0001

fl_imu_mountingangle: [0.0, 0.0, 0.0]
fr_imu_mountingangle: [0.0, 0.0, 0.0]
rl_imu_mountingangle: [0.0, 0.0, 0.0]
rr_imu_mountingangle: [0.0, 0.0, 0.0]

zupt_std: [0.02, 0.02, 0.02]
zihr_std: 0.1
zupt_dt: 0.01

if_use_multi_imu_constraint: true
relpos_dt: 0.1
relpos_std: 0.6

rotmat: [1, 0, 0,
         0, -1, 0,
         0, 0, -1]

base_in_bodyimu: [0.0, 0.0, 0.1]

robotpara:
  ox: 0.1934
  oy: 0.0465
  ot: 0.0955
  lc: 0.213
  lt: 0.213
